FROM node:14.17-alpine3.14 as build

# adding python for node-gyp
RUN apk add g++ make python3

COPY . /app
WORKDIR /app

# Installing packages
RUN npm ci --only=production

# Building TypeScript files
RUN npm run build:release

FROM node:14.17-alpine3.14
USER node
COPY --chown=node:node --from=build /app /app
WORKDIR /app
ENV NODE_ENV production

CMD ["npm", "run", "start:main:production"]
