#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")/
source "${DIR}/utils.sh"

if is_installed overmind; then
  exec overmind start --procfile="Procfile.dev"
else
  echo_red "Overmind not found!"
  echo "To install, run this:"
  echo_bold "  brew install overmind"
fi
