#!/bin/bash
# 
# Start tunnel for server using ngrok or localtunnel
# 

DIR=$(dirname "${BASH_SOURCE[0]}")/
source "${DIR}/utils.sh"

if [ -z ${TUNNEL_PORT} ]; then
  echo "TUNNEL_PORT must be set"
  exit 1
elif [ -z ${TUNNEL_SUBDOMAIN} ]; then
  echo "TUNNEL_SUBDOMAIN must be set"
  exit 1
fi

if is_installed ngrok; then
  exec ngrok http "${TUNNEL_PORT}" --subdomain="${TUNNEL_SUBDOMAIN}" --log=stdout
elif is_installed lt; then
  exec lt --port "${TUNNEL_PORT}" --subdomain "${TUNNEL_SUBDOMAIN}" --print-requests
else
  echo_red "No tunnel utility found!"
  echo "To install, run this:"
  echo_bold "  brew cask install ngrok # requires license"
  echo "            or"
  echo_bold "  npm install -g localtunnel # free"
fi
