#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

DIR=$(dirname "$0")
OLDFILE="${DIR}/../.env"
NEWFILE="${DIR}/../.env.development.local"
REGEX="^(APP_URL|WEBHOOK_PROXY_URL|NGROK_AUTHTOKEN|INSTANCE_NAME)=.*"
if [ -f "$OLDFILE" ] && [ !  -f "$NEWFILE" ]; then
  echo "Detected old .env file, moving to .env.development.local"
  mv "$OLDFILE" "$NEWFILE"
  echo "Moving global values back to .env file"
  cat "$NEWFILE" | grep -oE "${REGEX}" > "$OLDFILE"
  echo "Removing moved from .env.development.local file"
  sed -i '' -E "s/${REGEX}//" "$NEWFILE"
fi

. "$(dirname "$0")/create-env.sh"
